### PR TITLE
Image Manipulation Get Area Image Resolution copy, Xml load of Crop Areas, Test update

### PR DESCRIPTION
**Pull request by maxm74**
Image Manipulation Get Area Image Resolution copy,
Xml load of Crop Areas,
Test update

### CODE REVIEW

**Comment by lainz** [comment]
Can you create another pull request, but this time modifying only the files you need?

Like forking the repo again, and submitting only the changes to the current dev-branch.

Else is hard to know if I'm missing something.

**Comment by circular17** [comment]
I fixed the target branch. There are way less files. Though there are still a few differences that seems to come from a difference of version.

**Comment by circular17** [comment]
I suppose the extra differences are due to a commit in the source branch to match latest version, instead of rebasing on latest version: https://github.com/bgrabitmap/bgracontrols/pull/145/commits/b80025e4a0581852951796620ff5f650f30a567b

So those extra changes are redundant and not changing things in target branch. The real changes are in the other commit:
https://github.com/bgrabitmap/bgracontrols/pull/145/commits/c20d294a044d640a7807aa0d2f8ef086e4bb67fd

**Comment by lainz** [comment]
Ok I merged it. Thanks for your help.

**Comment by maxm74** [comment]
I never used rebase. What's the correct sequence? For example I've changed
something in my local folder.
I think first
git committ
And after?
Thanks

Il Sab 29 Lug 2023, 09:23 Leandro Oscar Ezequiel Diaz <
***@***.***> ha scritto:

**Comment by lainz** [comment]
What I do with forks is delete the fork and make a new one when the thing was merged. So no need to rebase.

**Pull request merged**
