### PR TITLE
Changed ktSector Operation to compute divisions for sectors. 

### PR DESCRIPTION
**Pull request by sganz**
Changed ktSector Operation to compute divisions for sectors. Removed SectorDivisions property. Some general clean up.

### CODE REVIEW

**Review by sganz — COMMENTED** [review]
Updating the knob to v2.10. Fixed up sector operations

**Review by sganz — COMMENTED** [review]
Approved

**Comment by circular17** [comment]
Hi Leandro,

> The branch on his/her github account.

Ah indeed updating a fork is not always obvious to do.

Hi Sandy,

Yes, sometimes starting fresh is the simplest option. It can take time to change our habits.

I've reviewed the changes and added your beautiful [test program](https://github.com/bgrabitmap/bgracontrols/tree/dev-bgracontrols/test/test_bgraknob). It all works fine and I've made [slight adjustements](c1b29bd7d542d044339e8381f626d77bdcd1946f) so that changing the knob type doesn't reset the value:.

I've added [default values for properties](5935692a77061b17d70610994078573b63884027) so that they are not written in the LFM file.

Thinking about it, the sector division doesn't seem necessary. The sector span is always equal to 1. So `CalcSectorFromValue` could simply round the value, or am I missing something? And `CalcValueFromSector` is in fact not necessary. What do you think?

Regards

**Comment by sganz** [comment]
I deleted my forked bgracontrols repo, hopefully that will be a better way to go. Let's see how that works out...

And yes, in looking at the CalSectorFromValue and CalcValueFromSector both seem like can be removed or cleaned up as sectorSpan will always be 1. I need to check to see if any of the range limit checks in CalcValueFromSector are really needed, as that may be the only thing, but have to take a look.  Good catch, simpler is better! Will do some more coding tonight and see if all good, and then attempt to not botch up the git work :) 

No problem changing anything in the tester program, glad it's useful, was helpful for me doing a lot of simple and repetitive testing.

Sandy

**Comment by circular17** [comment]
Yes, it is practical to have a test program to play with the components!

I've reviewed the new changes, and they look perfect. The modifications are clear and easy to distinguish. Thanks for the efforts, Sandy!

**Pull request merged**
